services:

  laravel-11:
    container_name: laravel-11
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./laravel-app:/var/www/html
    ports:
      - 9000:80
    
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel-11
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1